# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qsdev < Formula
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.1/qsdev_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "be3525cd7844406bec0f90dfbaad9f8408ad08a4003f6aba83b29ec57e3383b3"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.1/qsdev_0.3.1_Darwin_arm64.tar.gz"
      sha256 "2e367df93b122a473f156ae500add7d47d1cbc3c998eec735ea13cedf7b2a915"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.1/qsdev_0.3.1_Linux_x86_64.tar.gz"
      sha256 "a352df129b4dad4292d300f5286c1d41bddeb9c44c038c43a6e2ae3e615368f7"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.1/qsdev_0.3.1_Linux_arm64.tar.gz"
      sha256 "4a4baeb6fa4c5c03283bb5c5c8832e23c41b45abe6aeef1548491742b3172a91"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end
end
