# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qsdev < Formula
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.3/qsdev_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "83f52978b58f139d3f25e5f5e47d59b1b764d51e757720cbafe1afcef7a6b547"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.3/qsdev_0.3.3_Darwin_arm64.tar.gz"
      sha256 "0a618f19255631da8096932990090797df0deb1f38a6a49f6b86b3ffa8af06d6"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.3/qsdev_0.3.3_Linux_x86_64.tar.gz"
      sha256 "4ece8337ef58e49a35fe84343fbb8b9477cb9bae3a33d75ea24b179879af0852"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.3.3/qsdev_0.3.3_Linux_arm64.tar.gz"
      sha256 "905e5acc02cec2de9e0805bfdc63fa75a8f6c227881c25d0dbdf6db9406ad7b3"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end
end
