# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qsdev < Formula
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.4.0/qsdev_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "a86b4b43cd0743504d102583e2dc3c9d12a2815302fdec137b482f72979e9338"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.4.0/qsdev_0.4.0_Darwin_arm64.tar.gz"
      sha256 "16d74b84ccc26c12b9969724f008db775e7bb7a1122a2641aec35b7fbeffa1f5"

      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.4.0/qsdev_0.4.0_Linux_x86_64.tar.gz"
      sha256 "48b6b2f0e22f0b9f472f298f21a4e469b22576fdbdd56a55002fb1fe3d4cfb2c"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v0.4.0/qsdev_0.4.0_Linux_arm64.tar.gz"
      sha256 "d9bcffc30fb79ecdb3b334cb0ab01ce0ec4ebe269539265179f0f7880208c8ac"
      define_method(:install) do
        bin.install "qsdev"
        bash_completion.install "completions/qsdev.bash" => "qsdev"
        zsh_completion.install "completions/qsdev.zsh" => "_qsdev"
        fish_completion.install "completions/qsdev.fish"
      end
    end
  end
end
