# This file was generated by GoReleaser. DO NOT EDIT.
cask "qsdev" do
  version "0.7.4"

  on_macos do
    on_intel do
      sha256 "beb76ef973070abc4df5c14dad4dfec1838b805bb826c153529b1d724f0db95a"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "45f94ba5c0ebfd3a1011aa1e341596e6d2c82e9fe6683cac5c07a4c58a96cabb"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "432e9b1be0995a2db3c2bdbc94a90e36575feb3018fed53a95f5341136cafe53"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c529532e2935f89882bfd2e46659074051d872b76d264d46e0f27778759efd21"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "qsdev"
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qsdev"
  bash_completion "completions/qsdev.bash"
  fish_completion "completions/qsdev.fish"
  zsh_completion "completions/qsdev.zsh"

  # No zap stanza required

  caveats <<~EOS
    To verify your environment:
      qsdev doctor

    To initialize a project:
      qsdev init
  EOS
end
