# This file was generated by GoReleaser. DO NOT EDIT.
cask "qsdev" do
  version "0.7.8"

  on_macos do
    on_intel do
      sha256 "4e765bff3c60ad9d3703eef2291866d9ef1b31ecfb7a8c42bf6acc14ac3e90b0"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b70e8359ea3274824f604b22533c5aea6629daf39738f9c3c9948bb72a658bfd"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e5e3ebbdc6b2a2a83c4c06cc1a758730d52f460dca5ce3094a9a900450fd7b5"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ec6ddc3ceff01d7b6cbee70c5f469600a11e4d35575459fbbdb4c2c1657ce675"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "qsdev"
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qsdev"
  bash_completion "completions/qsdev.bash"
  fish_completion "completions/qsdev.fish"
  zsh_completion "completions/qsdev.zsh"

  # No zap stanza required

  caveats <<~EOS
    To verify your environment:
      qsdev doctor

    To initialize a project:
      qsdev init
  EOS
end
