# This file was generated by GoReleaser. DO NOT EDIT.
cask "qsdev" do
  version "0.7.7"

  on_macos do
    on_intel do
      sha256 "8fe6a662296020e05f2dce5b96b2897abf10822938991e984f3bfee061b774c2"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b699ec3781ad3e5db3b5f292bd6cf8592ce61c9449e1d21261837aa92daa32f6"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6913e3a3819a7242cd8d3f7f01b61ee66e6722c862d09548214901644e08262b"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "edd680bb94eea636ac265fac5be75a2c655757029b81fada20e98edbdd31b51c"
      url "https://github.com/Quantum-Serendipity/qsdev/releases/download/v#{version}/qsdev_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "qsdev"
  desc "Secure developer environment bootstrapping tool"
  homepage "https://github.com/Quantum-Serendipity/qsdev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qsdev"
  bash_completion "completions/qsdev.bash"
  fish_completion "completions/qsdev.fish"
  zsh_completion "completions/qsdev.zsh"

  # No zap stanza required

  caveats <<~EOS
    To verify your environment:
      qsdev doctor

    To initialize a project:
      qsdev init
  EOS
end
